# dein_lazy.toml
# EOL:LF / code:UTF-8

[[plugins]] # Vimヘルプの日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # ツリー型エクスプローラー NERDTree
repo = 'preservim/nerdtree'

# 曖昧入力でファイルを開く fzf {
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
# } fzf
